// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtwBUGKioYH6mIxDsy1HOOpg9OtbuVI4',
    appId: '1:524733748840:web:49b6e2397e319073fc0ddd',
    messagingSenderId: '524733748840',
    projectId: 'nlc-india-df337',
    authDomain: 'nlc-india-df337.firebaseapp.com',
    storageBucket: 'nlc-india-df337.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB37KrnFiy0NrNWZXyEyz55JbwQdY6EkJ8',
    appId: '1:524733748840:android:767bf9b391bae86afc0ddd',
    messagingSenderId: '524733748840',
    projectId: 'nlc-india-df337',
    storageBucket: 'nlc-india-df337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZX5XMRd7WDsNYHMdn0lMEd1cF3U4CjTw',
    appId: '1:524733748840:ios:bbfacc8449dddaf0fc0ddd',
    messagingSenderId: '524733748840',
    projectId: 'nlc-india-df337',
    storageBucket: 'nlc-india-df337.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZX5XMRd7WDsNYHMdn0lMEd1cF3U4CjTw',
    appId: '1:524733748840:ios:bbfacc8449dddaf0fc0ddd',
    messagingSenderId: '524733748840',
    projectId: 'nlc-india-df337',
    storageBucket: 'nlc-india-df337.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYtwBUGKioYH6mIxDsy1HOOpg9OtbuVI4',
    appId: '1:524733748840:web:8e35a17feaf5a6eafc0ddd',
    messagingSenderId: '524733748840',
    projectId: 'nlc-india-df337',
    authDomain: 'nlc-india-df337.firebaseapp.com',
    storageBucket: 'nlc-india-df337.firebasestorage.app',
  );
}
